"""
backend/routers/analytics.py
==============================
FastAPI router that exposes pre-computed analytics derived from the
training dataset.  All data is served from a single analytics.json cache
generated by scripts/precompute_analytics.py.

Endpoints
---------
GET /analytics/hourly-trend        — Average demand per hour of day (0-23)
GET /analytics/weather-impact      — Mean/std demand grouped by weather type
GET /analytics/peak-heatmap        — Hour x RoadType demand matrix
GET /analytics/geo-demand          — Per-geohash mean demand with lat/lon
GET /analytics/temp-bins           — Mean demand across temperature ranges
GET /analytics/road-type-stats     — Aggregated demand per road type
GET /analytics/demand-distribution — Histogram of the demand target variable
GET /analytics/dataset-stats       — High-level dataset metadata
"""

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/analytics", tags=["Analytics"])

ROOT = Path(__file__).parent.parent.parent
ANALYTICS_PATH = ROOT / "model_artifacts" / "analytics.json"

_cache: dict | None = None


def _load() -> dict | None:
    """
    @brief Load analytics.json into memory, caching after the first read.

    @return  Parsed analytics dict, or None if the file does not exist.
    """
    global _cache
    if _cache is None:
        if not ANALYTICS_PATH.exists():
            return None
        with open(ANALYTICS_PATH) as f:
            _cache = json.load(f)
    return _cache


def _get(key: str):
    """
    @brief Retrieve a named section from the analytics cache.

    @param key  Top-level key in analytics.json (e.g. "hourly_trend").
    @return     The corresponding value from the cache.
    @raises HTTPException(503)  If analytics.json has not been generated yet.
    """
    data = _load()
    if data is None:
        raise HTTPException(
            503,
            "Analytics not computed yet. Run: python scripts/precompute_analytics.py",
        )
    return data[key]


@router.get("/hourly-trend")
async def hourly_trend():
    """
    @brief Return average traffic demand aggregated by hour of day.

    @return  List of dicts with keys: hour, mean_demand, std_demand, count.
    """
    return _get("hourly_trend")


@router.get("/weather-impact")
async def weather_impact():
    """
    @brief Return mean and std demand for each weather condition.

    @return  List of dicts with keys: weather, mean_demand, std_demand, count.
    """
    return _get("weather_impact")


@router.get("/peak-heatmap")
async def peak_heatmap():
    """
    @brief Return a flattened hour x road-type demand matrix.

    @return  List of dicts with keys: hour, road_type, mean_demand.
    """
    return _get("peak_heatmap")


@router.get("/geo-demand")
async def geo_demand():
    """
    @brief Return per-geohash average demand with decoded coordinates.

    @return  List of dicts with keys: geohash, lat, lon, mean_demand.
    """
    return _get("geo_demand")


@router.get("/temp-bins")
async def temp_bins():
    """
    @brief Return mean demand bucketed into temperature ranges.

    Bins: <0C, 0-10C, 10-20C, 20-30C, >30C.

    @return  List of dicts with keys: temp_bin, mean_demand, count.
    """
    return _get("temp_bins")


@router.get("/road-type-stats")
async def road_type_stats():
    """
    @brief Return aggregate demand statistics per road type.

    @return  List of dicts with keys: road_type, mean, median, std, count.
    """
    return _get("road_type_stats")


@router.get("/demand-distribution")
async def demand_distribution():
    """
    @brief Return a histogram of the demand target variable.

    @return  Dict with keys: counts, bin_edges, mean, median, p95.
    """
    return _get("demand_distribution")


@router.get("/dataset-stats")
async def dataset_stats():
    """
    @brief Return high-level dataset metadata.

    @return  Dict with keys: total_rows, unique_geohashes, unique_days,
             weather_types, road_types.
    """
    return _get("dataset_stats")
